[[resource_sync]]
name = "huninprogress"
[resource_sync.config]
repo = "huninprogress/playbook"
branch = "master"
resource_path = [
  "syncs/stacks",
  "syncs/variables.toml",
  "syncs/servers.toml",
  "syncs/resources.toml"
]
delete = true
include_variables = true
