name: komodo

networks:
  komodo:
    name: komodo
    driver: bridge

services:
  mongo:
    image: mongo:${MONGO_VERSION:-7.0.35}
    container_name: komodo-mongo
    networks:
      - komodo
    labels:
      komodo.skip: # Prevent Komodo from stopping this with StopAllContainers
    command: --quiet --wiredTigerCacheSizeGB 0.25
    restart: unless-stopped
    volumes:
      - ${KOMODO_MONGO_DATA:-/etc/komodo/mongo/data}:/data/db
      - ${KOMODO_MONGO_CONFIG:-/etc/komodo/mongo/config}:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KOMODO_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${KOMODO_DATABASE_PASSWORD}

  komodo:
    image: ghcr.io/moghtech/komodo-core:${KOMODO_IMAGE_TAG:-2}
    container_name: komodo
    init: true
    restart: unless-stopped
    depends_on:
      - mongo
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
    volumes:
      - ${KOMODO_KEYS_PATH:-/etc/komodo/keys}:/config/keys
      - ${KOMODO_BACKUPS_PATH:-/etc/komodo/backups}:/backups
    ports:
      - 9120:9120
    networks:
      - komodo
