networks:
  ollama:
    driver: bridge
    name: ollama
  # newt:
  #   external: true
  # cloudflared:
  #   external: true
  # traefik:
  #   external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - ollama
    # volumes:
    #   - /mnt/mp0/ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
