networks:
  dind:
    name: dind
    driver: bridge

services:
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    networks:
      - dind
    restart: unless-stopped
    command: ["dockerd", "-H", "tcp://0.0.0.0:2375", "--tls=false"]
