services:

  garage:
    image: dxflrs/garage:v2.3.0
    network_mode: "host"
    restart: unless-stopped
    container_name: garage
    # ports:
    #   - "3900:3900"
    #   - "3901:3901"
    #   - "3902:3902"
    #   - "3903:3903"
    volumes:
      - ./garage.toml:/etc/garage.toml
      - /mnt/mp0/garage/meta:/var/lib/garage/meta
      - /mnt/mp0/garage/data:/var/lib/garage/data

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    # ports:
    #   - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
