services:
  headscale:
    image: headscale/headscale:${HEADSCALE_VERSION:-v0.28.0}
    container_name: headscale
    volumes:
      - /mnt/default/volumes/headscale/config:/etc/headscale
      - /mnt/default/volumes/headscale/lib:/var/lib/headscale
      - /mnt/default/volumes/headscale/run:/var/run/headscale
    command: serve
    restart: unless-stopped
    ports:
      - 8080:8080

  headplane:
    image: ghcr.io/tale/headplane:${HEADPLANE_VERSION:-v0.6.3}
    container_name: headplane
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /mnt/default/volumes/headplane/config.yaml:/etc/headplane/config.yaml
      - /mnt/default/volumes/headplane/lib/headplane:/var/lib/headplane
