networks:
  public:
    name: public
    external: true

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:${FORGEJO_VERSION:-15.0.2}
    container_name: forgejo
    environment:
      - USER_UID=${PUID:-100000}
      - USER_GID=${PGID:-100000}
      - FORGEJO__server__ROOT_URL=${FORGEJO_URL}
    restart: unless-stopped
    networks:
      - public
    volumes:
      - ${FORGEJO_DATA:-/mnt/rust/forgejo}:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: "true"
      traefik.docker.network: public
      traefik.http.routers.forgejo.rule: Host(`${FORGEJO_HOST}`)
      traefik.http.routers.forgejo.entrypoints: web
      traefik.http.services.forgejo.loadbalancer.server.port: 3000
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
