#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_DIR="$REPO_ROOT/komodo/periphery"
ENV_FILE="$COMPOSE_DIR/.env"

# ── Colors ────────────────────────────────────────────────────────────────────
BOLD='\033[1m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

header()  { echo -e "\n${BOLD}${CYAN}$*${RESET}"; }
success() { echo -e "${GREEN}✔  $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠  $*${RESET}"; }

# ── Prompt helper ─────────────────────────────────────────────────────────────
ask() {
  local var="$1" prompt="$2" default="$3" mode="${4:-}"

  if [[ -n "$default" ]]; then
    printf "${BOLD}%s${RESET} [%s]: " "$prompt" "$default"
  else
    printf "${BOLD}%s${RESET}: " "$prompt"
  fi

  if [[ "$mode" == "secret" ]]; then
    read -rs value; echo
  else
    read -r value
  fi

  [[ -z "$value" ]] && value="$default"
  printf -v "$var" '%s' "$value"
}

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
echo "  Komodo Periphery — agent deployment script"
echo -e "${RESET}"

# ── Existing .env warning ─────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at $ENV_FILE"
  printf "${BOLD}Overwrite it?${RESET} [y/N]: "
  read -r confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

# ── Collect variables ─────────────────────────────────────────────────────────
header "Core connection"
echo -e "  ${YELLOW}Tip:${RESET} find the Core address in Komodo UI → Settings → Authentication"
echo
ask PERIPHERY_CORE_ADDRESS "Komodo Core WebSocket address" "ws://<CORE_IP>:9120"
ask PERIPHERY_CONNECT_AS   "Name for this server in the UI" "$HOSTNAME"

header "Authentication"
echo -e "  ${YELLOW}Tip:${RESET} generate an onboarding key in Komodo UI → Settings → Onboarding"
echo -e "  The onboarding key lets periphery auto-register. You can remove it after first connect."
echo
ask PERIPHERY_ONBOARDING_KEY  "Onboarding key (O-...)" ""

header "Storage"
ask PERIPHERY_ROOT_DIRECTORY "Periphery root directory (stacks/repos live here)" "/etc/komodo"

header "General"
ask TZ "Timezone" "Asia/Ho_Chi_Minh"

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by deploy-periphery.sh on $(date)

KOMODO_IMAGE_TAG=2

TZ=${TZ}

PERIPHERY_CORE_ADDRESS=${PERIPHERY_CORE_ADDRESS}
PERIPHERY_CONNECT_AS=${PERIPHERY_CONNECT_AS}
PERIPHERY_ONBOARDING_KEY=${PERIPHERY_ONBOARDING_KEY}
PERIPHERY_CORE_PUBLIC_KEYS=file:/config/keys/core.pub
PERIPHERY_ROOT_DIRECTORY=${PERIPHERY_ROOT_DIRECTORY}
PERIPHERY_INCLUDE_DISK_MOUNTS=/etc/hostname
EOF

success ".env written to $ENV_FILE"

# ── Deploy ────────────────────────────────────────────────────────────────────
echo
printf "${BOLD}Deploy now?${RESET} [Y/n]: "
read -r deploy
[[ "$deploy" =~ ^[Nn]$ ]] && { echo "Skipped. Run manually: docker compose -f $COMPOSE_DIR/docker-compose.yaml up -d"; exit 0; }

echo
docker compose -f "$COMPOSE_DIR/docker-compose.yaml" --env-file "$ENV_FILE" up -d

echo
success "Periphery agent is up!"
echo -e "  Server ${BOLD}${PERIPHERY_CONNECT_AS}${RESET} should appear in Komodo UI → Servers within a few seconds."
