#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_DIR="$REPO_ROOT/coordinators/komodo/core"
ENV_FILE="$COMPOSE_DIR/.env"

# ── Colors ────────────────────────────────────────────────────────────────────
BOLD='\033[1m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

header()  { echo -e "\n${BOLD}${CYAN}$*${RESET}"; }
success() { echo -e "${GREEN}✔  $*${RESET}"; }
warn()    { echo -e "${YELLOW}⚠  $*${RESET}"; }
die()     { echo -e "${RED}✘  $*${RESET}" >&2; exit 1; }

# ── Prompt helper ─────────────────────────────────────────────────────────────
# Usage: ask VAR_NAME "Prompt text" "default value"
# Reads into the variable named by VAR_NAME. Hides input when 4th arg is "secret".
ask() {
  local var="$1" prompt="$2" default="$3" mode="${4:-}"
  local display_default="$default"
  [[ "$mode" == "secret" && -n "$default" ]] && display_default="(auto-generated)"

  if [[ -n "$default" ]]; then
    printf "${BOLD}%s${RESET} [%s]: " "$prompt" "$display_default"
  else
    printf "${BOLD}%s${RESET}: " "$prompt"
  fi

  if [[ "$mode" == "secret" ]]; then
    read -rs value; echo
  else
    read -r value
  fi

  [[ -z "$value" ]] && value="$default"
  printf -v "$var" '%s' "$value"
}

gen_secret() { openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '=+/' | head -c 32; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}"
echo "  ██╗  ██╗ ██████╗ ███╗   ███╗ ██████╗ ██████╗  ██████╗"
echo "  ██║ ██╔╝██╔═══██╗████╗ ████║██╔═══██╗██╔══██╗██╔═══██╗"
echo "  █████╔╝ ██║   ██║██╔████╔██║██║   ██║██║  ██║██║   ██║"
echo "  ██╔═██╗ ██║   ██║██║╚██╔╝██║██║   ██║██║  ██║██║   ██║"
echo "  ██║  ██╗╚██████╔╝██║ ╚═╝ ██║╚██████╔╝██████╔╝╚██████╔╝"
echo "  ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝ ╚═════╝ ╚═════╝  ╚═════╝"
echo -e "${RESET}  Core deployment script\n"

# ── Existing .env warning ─────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  warn ".env already exists at $ENV_FILE"
  printf "${BOLD}Overwrite it?${RESET} [y/N]: "
  read -r confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 0; }
fi

# ── Collect variables ─────────────────────────────────────────────────────────
header "Storage paths"
ask KOMODO_MONGO_DATA      "MongoDB data directory"      "/etc/komodo/mongo/data"
ask KOMODO_MONGO_CONFIG    "MongoDB config directory"    "/etc/komodo/mongo/config"
ask KOMODO_KEYS_PATH       "Keys directory"              "/etc/komodo/keys"
ask KOMODO_BACKUPS_PATH    "Backups directory"           "/etc/komodo/backups"

header "Database"
ask KOMODO_DATABASE_USERNAME "MongoDB username"          "admin"
ask KOMODO_DATABASE_PASSWORD "MongoDB password"          "" secret

header "Core settings"
ask KOMODO_TITLE           "Browser tab title"           "Komodo"
ask TZ                     "Timezone"                    "Asia/Ho_Chi_Minh"

header "Initial admin account"
ask KOMODO_INIT_ADMIN_USERNAME "Admin username"          "admin"
ask KOMODO_INIT_ADMIN_PASSWORD "Admin password"          "" secret

header "Secrets (leave blank to auto-generate)"
ask KOMODO_WEBHOOK_SECRET  "Webhook secret"              "$(gen_secret)" secret
ask KOMODO_JWT_SECRET      "JWT secret"                  "$(gen_secret)" secret
ask KOMODO_JWT_TTL         "JWT token TTL"               "1-day"

header "Monitoring"
ask KOMODO_MONITORING_INTERVAL "Monitoring interval"    "15-sec"

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Generated by deploy-komodo.sh on $(date)

KOMODO_IMAGE_TAG=2
MONGO_VERSION=7.0.35

KOMODO_MONGO_DATA=${KOMODO_MONGO_DATA}
KOMODO_MONGO_CONFIG=${KOMODO_MONGO_CONFIG}
KOMODO_KEYS_PATH=${KOMODO_KEYS_PATH}
KOMODO_BACKUPS_PATH=${KOMODO_BACKUPS_PATH}

KOMODO_DATABASE_USERNAME=${KOMODO_DATABASE_USERNAME}
KOMODO_DATABASE_PASSWORD=${KOMODO_DATABASE_PASSWORD}

TZ=${TZ}

KOMODO_TITLE=${KOMODO_TITLE}
KOMODO_PERIPHERY_PUBLIC_KEY=file:/config/keys/periphery.pub
KOMODO_LOCAL_AUTH=true
KOMODO_INIT_ADMIN_USERNAME=${KOMODO_INIT_ADMIN_USERNAME}
KOMODO_INIT_ADMIN_PASSWORD=${KOMODO_INIT_ADMIN_PASSWORD}
KOMODO_FIRST_SERVER_NAME=Local
KOMODO_WEBHOOK_SECRET=${KOMODO_WEBHOOK_SECRET}
KOMODO_JWT_SECRET=${KOMODO_JWT_SECRET}
KOMODO_JWT_TTL=${KOMODO_JWT_TTL}
KOMODO_MONITORING_INTERVAL=${KOMODO_MONITORING_INTERVAL}
EOF

success ".env written to $ENV_FILE"

# ── Deploy ────────────────────────────────────────────────────────────────────
echo
printf "${BOLD}Deploy now?${RESET} [Y/n]: "
read -r deploy
[[ "$deploy" =~ ^[Nn]$ ]] && { echo "Skipped. Run manually: docker compose -f $COMPOSE_DIR/docker-compose.yaml up -d"; exit 0; }

echo
docker compose -f "$COMPOSE_DIR/docker-compose.yaml" --env-file "$ENV_FILE" up -d

echo
echo -e "  Login: ${BOLD}${KOMODO_INIT_ADMIN_USERNAME}${RESET} / (the password you set)"
