networks:
  dind:
    external: true

services:
  runner:
    image: "data.forgejo.org/forgejo/runner:12"
    networks:
      - dind
    container_name: "runner"
    environment:
      DOCKER_HOST: tcp://dind:2375
    volumes:
      - /mnt/mp0/forgejo-runner/data:/data
    restart: "unless-stopped"
    command: "forgejo-runner daemon --config runner-config.yml"
