networks:
  ## traefik for internal, newt for public
  traefik:
    external: true

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      # Set your timezone, e.g., America/New_York or Europe/Warsaw
      - TZ=Etc/UTC
      # Optional: Set the published server URL if behind a reverse proxy
      - JELLYFIN_PublishedServerUrl=${URL}
    volumes:
      # Map container paths to your host machine paths
      - /mnt/mp0/var/jellyfin/config:/config
      - /mnt/mp0/var/jellyfin/cache:/cache
      - /mnt/media:/media # :ro means read-only
      # Add more media library mappings as needed
    restart: unless-stopped
    # Optional: uncomment the lines below to enable hardware transcoding if you have a compatible GPU
    # devices:
    #   - /dev/dri:/dev/dri # Intel iGPU (VAAPI)
    #   - /dev/nvidiactl:/dev/nvidiactl # Nvidia (NVENC)
    #   - /dev/nvidia-uvm:/dev/nvidia-uvm
    #   - /dev/nvidia-modeset:/dev/nvidia-modeset
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_HOST}`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video]
