services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      # Optional: Set the published server URL if behind a reverse proxy
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_HOST}
    volumes:
      - ${JELLYFIN_CONFIG:-/mnt/rust/jellyfin/config}:/config
      - ${JELLYFIN_CACHE:-/mnt/rust/jellyfin/cache}:/cache
      - ${MEDIA_PATH:-/mnt/media}:/media:ro
    restart: unless-stopped
    # Optional: uncomment the lines below to enable hardware transcoding if you have a compatible GPU
    # devices:
    #   - /dev/dri:/dev/dri # Intel iGPU (VAAPI)
    #   - /dev/nvidiactl:/dev/nvidiactl # Nvidia (NVENC)
    #   - /dev/nvidia-uvm:/dev/nvidia-uvm
    #   - /dev/nvidia-modeset:/dev/nvidia-modeset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video]
